### ISSUE TITLE
Axios security vulnerability

### ISSUE THREAD

**Issue by papey** [EdwardJFox/challonge-ts#1]
Thanks a lot for this lib,

There is a vulnerability in the Axios version used in this project

```
warning challonge-ts > axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
```

Can update it if you want.

Thanks.

**Comment by EdwardJFox** [comment]
Hey thanks for letting me know, and apologies, I've let this library be out there with no love! I've bumped all the packages, and published v0.0.2 to npm.

If you want something slightly more updated with a few bugs fixed, I would recommend checking out the fork of this repo https://github.com/the-nuel/challonge-ts which is also published on npm. This repo may be fixed at some point in the future as it needs quite a few changes, but if you have any issues with my version, this fork may be a drop in replacement and solve any issues which come up.

Thanks again!
